server:
  port: 50000

spring:
  cache:
    type: simple

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  okhttp:
    enabled: true
