server:
  port: 50000

spring:
  cache:
    type: simple

feign:
  okhttp:
    enabled: true
  httpclient:
    connection-timeout: 5000


management:
  health:
    livenessstate:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
